### ISSUE TITLE
Customizable text

### ISSUE THREAD

**Issue by zenkyuv** [haumea-group/namaka#101]
for the customizable text,

- maybe it will be done with shadow `<slot>` elements?
- maybe it could be component html attributes?
- most likely: it might have to be an installation option for namaka specified in `prepare-components.ts` and passed into a special "options model" or some such madness
- maybe it actually can be a shadow `<slot>` of the whole modal system, (`<namaka-modals>`).. but it'd still have to be specified during the modal installation in `install-modal-system.ts`

_Originally posted by @chase-moskal in https://github.com/haumea-group/namaka/issues/83#issuecomment-1130266114_

**Comment by chase-moskal** [comment]
@zenkyuv closing this ticket in favor of newer #119
