### ISSUE TITLE
⭐ Five-star rating functionality

### ISSUE THREAD

**Issue by zenkyuv** [haumea-group/namaka#2]
My first ever issue or just some sort of thing to do on issues panel 🌠

- render the appropriate number of (filled) stars
  - on click
  - on hover
- how it should look like: 
![image](https://user-images.githubusercontent.com/79974168/166334861-42827bd8-db3a-465a-9078-82fb94eda0d0.png)

**Comment by zenkyuv** [comment]
of course give me some some insights on what should I add or change here, I've just added simple steps for now

**Comment by chase-moskal** [comment]
@zenkyuv looks like you've made some good progress in your branch,

whether you're finished or not, but let's complete this task in #24 by integrating it into the other review components
