### ISSUE TITLE
⚖️ organize icons with attribution and licensing

### ISSUE THREAD

**Issue by chase-moskal** [haumea-group/namaka#27]

**Comment by PaulAroo** [comment]
@chase-moskal  could we just leave links to license in a `readme` file, just like [here in xiome?](https://github.com/chase-moskal/xiome/blob/master/s/framework/icons/README.md)

**Comment by chase-moskal** [comment]
technically speaking, xiome's technique is not sufficient and needs to be improved.

a better example, is how we attribute icon licensing in benevolent: https://github.com/benevolent-games/benevolent.games/tree/master/s/web/icons

icons should be categorized into folders, and then a license file added to each folder, along with the appropriate notes about the modifications made.

**Comment by PaulAroo** [comment]
Alright, then I guess we need to discuss with the designer in order to pinpoint which part of the iconify library the icons from the Figma designs came from... or maybe just figure it out ourselves

**Comment by yespired** [comment]
I will like to be assigned this ticket @chase-moskal
