### ISSUE TITLE
📜 formalize list of all new components in the readme

### ISSUE THREAD

**Issue by chase-moskal** [haumea-group/namaka#46]
names and descriptions of every component we need to have, examples:

**`<namaka-comment-list>`**  
list of comments (which may also be reviews) that has a "load more" button, and sorting features

**`<namaka-bans>`**  
list of users that have been banned

- this work is not to write full or comprehensive documentation for each component
- what we really want, is to distill what components we really need, and to finally decide on the actual names of those components

**Comment by zenkyuv** [comment]
Sorry ive clicked discord push button when scrolling through projects xd
