### ISSUE TITLE
📧 modal for support email to report naughty comments/users

### ISSUE THREAD

**Issue by chase-moskal** [haumea-group/namaka#59]
building a report system will take too long. so we'll do it later.

in the meantime, we need a modal display, that tells users to email a support email address, to report naughty comments and users.

the modal should display a copiable text block, which includes the user's nickname, `userId`, and the `commentId`, and tells the reporter user to paste this into the support email.

**Comment by chase-moskal** [comment]
unclear if @zenkyuv or @joshuaolusayo is currently working on this task?

who's working on this frontend ticket to create the report modal?

**Comment by zenkyuv** [comment]
> unclear if @zenkyuv or @joshuaolusayo is currently working on this task?
> 
> who's working on this frontend ticket to create the report modal?

I am working on it
